### PR TITLE
Morgue with docker and docker-compose

### PR DESCRIPTION
**Pull request by geshan**

### CODE REVIEW

**Comment by liuzhen** [comment]
why closed?

**Comment by geshan** [comment]
No one responded for weeks.

**Comment by liuzhen** [comment]
I have tried your branch with simply create a post:
```
morgue_1_5cc9b6a5073a | [Tue Apr 16 07:27:19 2019] Array
morgue_1_5cc9b6a5073a | (
morgue_1_5cc9b6a5073a |     [id] =>
morgue_1_5cc9b6a5073a |     [error] => SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'problem_type' cannot be null
morgue_1_5cc9b6a5073a | )
```
don't know if it is upstream issue.

**Comment by liuzhen** [comment]
the config of `config/docker.json` lacks those items

**Comment by liuzhen** [comment]
and no way to update config without rebuilding docker?

**Comment by geshan** [comment]
It was working for me maybe the migration was broken.

**Pull request closed without merging**
